server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /chh-wx-api

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/emos?useUnicode=true&characterEncoding=UTF-8
      username: 
      password: 
      initial-size: 4
      max-active: 8
      min-idle: 4
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  redis:
    database: 0
    host: localhost
    port: 6379
    password: 
    jedis:
      pool:
        max-active: 1000
        max-idle: 16
        max-wait: -1ms
        min-idle: 8
    timeout: 5000ms

  data:
    mongodb:
      host: localhost
      port: 27017
      database: emos
      authentication-database: admin
      username: root
      password: 

  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: 
    password: 

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.chh.wx.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.chh.wx.db.dao: warn
  pattern:
    console: "%d{HH:mm:ss}  %-5level %msg%n"

emos:
  jwt:
    #密钥
    secret: abc123456
    #令牌过期时间 day
    expire: 5
    #令牌缓存时间 day
    cache-expire: 10

  face:
    createFaceModelUrl: 
    checkinUrl: 

  email:
    system: 
    hr: 

  image-folder: /Users/apple/Downloads/ImageFolder

  code: HelloWorld

  recieveNotify: http://192.168.2.2:8080/chh-wx-api/meeting/recieveNotify

workflow:
  url: http://192.168.2.6:9090/emos-workflow

trtc:
  appid: 
  key: 
  #时间一天 24 * 3600
  expire: 86400

wx:
  app-id: 
  app-secret: 
